package shared.util;

public enum EventType {
    LOGIN_RESULT,
    LOGIN_REQUEST,
    REGISTER_REQUEST,
    REGISTER_RESULT,
    GETMOVIES_REQUEST,
    GETMOVIES_RESULT,
    CLOSE_REQUEST,
    CLOSE_RESULT,
    SAVENEWINFO_REQUEST,
    SAVENEWINFO_RESULT,
    GETUSER_REQUEST,
    GETUSER_RESULT,
    ADMIN_CHECK_REQUEST,
    ADMIN_CHECK_RESULT
}
