package shared.util;

public enum EventType {
    LOGIN_RESULT,
    LOGIN_REQUEST,
    REGISTER_REQUEST,
    REGISTER_RESULT,
    GETMOVIES_REQUEST,
    GETMOVIES_RESULT,
    CLOSE_REQUEST,
    CLOSE_RESULT,
    SAVENEWINFO_REQUEST,
    SAVENEWINFO_RESULT,
    GETUSER_REQUEST,
    GETUSER_RESULT,
    ADDMOVIE_REQUEST,
    ADDMOVIE_RESULT,
    EDITMOVIE_RESQUEST,
    EDITMOVIE_RESULT,
    REMOVEMOVIE_REQUEST,
    REMOVEMOVIE_RESULT,
    RESERVEMOVIE_REQUEST,
    RESERVEMOVIE_RESULT

}
